config/routes.rb
SecretShareAjax::Application.routes.draw do
  resources :users, :only => [:create, :new, :show, :index] do
    resources :secrets, only: [:new]
    resource :friendship, only: [:create, :destroy]
  end

  resources :secrets, only: [:create]

  resource :session, :only => [:create, :destroy, :new]

  root :to => "users#show"
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :in_friend_id, :out_friend_id

  validates :in_friend, :out_friend, presence: true

  belongs_to(
    :in_friend,
    class_name: "User",
    foreign_key: :in_friend_id,
    primary_key: :id,
    inverse_of: :in_friendships
  )

  belongs_to(
    :out_friend,
    class_name: "User",
    foreign_key: :out_friend_id,
    primary_key: :id,
    inverse_of: :out_friendships
  )

  def self.can_friend?(out_friend_id, in_friend_id)
    return false if out_friend_id == in_friend_id
    !Friendship.exists?(out_friend_id: out_friend_id, in_friend_id: in_friend_id)
  end

  def self.can_unfriend?(out_friend_id, in_friend_id)
    Friendship.exists?(out_friend_id: out_friend_id, in_friend_id: in_friend_id)
  end
end

app/models/secret.rb
class Secret < ActiveRecord::Base
  attr_accessible :author_id, :recipient_id, :title, :tag_ids

  belongs_to :author, :class_name => "User"
  belongs_to :recipient, :class_name => "User"

  has_many :secret_taggings, inverse_of: :secret

  has_many :tags, through: :secret_taggings, source: :tag

  validates :author_id, :recipient_id, :title, :presence => true
end

app/models/secret_tagging.rb
class SecretTagging < ActiveRecord::Base
  attr_accessible :secret_id, :tag_id

  validates :secret, :tag, presence: true

  belongs_to :secret, inverse_of: :secret_taggings
  belongs_to :tag, inverse_of: :secret_taggings
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  validates :name, presence: true, uniqueness: true

  has_many :secret_taggings, inverse_of: :tag
  has_many :secrets, through: :secret_taggings, source: :secret
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password
  attr_reader :password

  has_many(
    :authored_secrets,
    :class_name => "Secret",
    :foreign_key => :author_id
  )

  has_many(
    :received_secrets,
    :class_name => "Secret",
    :foreign_key => :recipient_id
  )

  has_many(
    :in_friendships,
    class_name: "User",
    foreign_key: :in_friend_id,
    primary_key: :id,
    inverse_of: :in_friend
  )

  has_many(
    :out_friendships,
    class_name: "User",
    foreign_key: :out_friend_id,
    primary_key: :id,
    inverse_of: :out_friend
  )

  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true
  validates :username, :presence => true

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create

    @friendship = Friendship.new( out_friend_id: current_user.id,
                                  in_friend_id: params[:user_id])
    @friendship.save!

    head :ok
  end

  def destroy
    @friendship = Friendship.where(out_friend_id: current_user.id,
                                   in_friend_id: params[:user_id])
    @friendship[0].destroy unless @friendship.nil?

    head :ok
  end
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  def new
    @secret = Secret.new
    @recipient_id = params[:user_id]
  end

  def create
    @secret = Secret.new(params[:secret])
    @secret.author_id = current_user.id

    if @secret.save
      render :json => {secret: @secret, tags: @secret.tags }
      # redirect_to user_url(params[:secret][:recipient_id])
    else
      head :bad_request
      # render :json => @secret.errors.full_messages
    end

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_no_current_user!, :only => [:create, :new]
  before_filter :require_current_user!, :only => [:destroy]

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      render :json => "Credentials were wrong"
    else
      self.current_user = user
      redirect_to user_url(user)
    end
  end

  def destroy
    logout_current_user!
    redirect_to new_session_url
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, :only => [:show]
  before_filter :require_no_current_user!, :only => [:create, :new]

  def create
    @user = User.new(params[:user])

    if @user.save
      self.current_user = @user
      redirect_to user_url(@user)
    else
      render :json => @user.errors.full_messages
    end
  end

  def new
    @user = User.new
  end

  def show
    if params.include?(:id)
      @user = User.find(params[:id])
    else
      redirect_to user_url(current_user)
    end
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def current_user=(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout_current_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to new_session_url if current_user.nil?
  end

  def require_no_current_user!
    redirect_to user_url(current_user) unless current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/_form.html.erb
<form action="<%= user_friendship_url(user) %>" method="post">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
  <input type="submit" value="Befriend">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecretShareAjax</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if !current_user.nil? %>
  <ul>
    <li>Logged in as: <%= current_user.username %></li>
    <li><%= button_to "Logout", session_url, :method => :delete %></li>
  </ul>
<% end %>

<%= yield %>

</body>
</html>

app/views/secrets/_form.html.erb
<form action="<%= secrets_url %>" method="post" id="secretForm">
  <input  type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">

  <input  type="hidden"
          name="secret[recipient_id]"
          value="<%= recipient_id %>">

  <p>
    <label>Title:
      <input type="text" name="secret[title]">
    </label>
  </p>

  <p>
    <label>Tags:<br>
      <div id="secret-tag-selects"></div>
      <a href="#" id="newTag">Add a Tag!</a>
    </label>
  </p>

  <p>
    <input type="submit" value="Create Secret">
  </p>
</form>

<script type="application/json" id="bootstrapped_tags_json">
  { "tags": <%= tags.to_json.html_safe %>}
</script>

<script type="text/template" id="secret_select_template">
  <p><select name="secret[tag_ids][]">
    <%% _(tags).each(function(tag) { %>
      <option value="<%%= tag.id %>"><%%= tag.name %></option>
    <%% }); %>
  </select></p>
</script>

<script type="application/javascript">

  var addSecretTagSelect = function(tags) {
    var templateCode = $("#secret_select_template").html();
    var templateFn = _.template(templateCode);
    var renderedContent = templateFn({tags: tags});
    $("#secret-tag-selects").append(renderedContent);
  }

  $('#newTag').click(function() {
    var data = JSON.parse($('#bootstrapped_tags_json').html());
    var tags = data["tags"];
    addSecretTagSelect(tags);
  });
</script>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
     id="user_username"
     name="user[username]"
     type="text">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" value="<%= message %>">
</form>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.username %>
      <% unless current_user == user %>
        <% is_friend = Friendship.can_unfriend?(current_user.id, user.id) %>

        <span class="friend-buttons <%= (is_friend ? 'can-unfriend' : 'can-friend').html_safe%>">
          <button class="friend" data-id="<%= user.id %>">Friend</button>
          <button class="unfriend" data-id="<%= user.id %>">Unfriend</button>
        </span>
      <% end %>
    </li>
  <% end %>
</ul>

<script>

  var toggleFriendButtons = function($button) {
    var $span = $button.parent();
    $span.toggleClass('can-unfriend');
    $span.toggleClass('can-friend');
  }

  $("ul").on("click", "button.friend", function(event){
    event.preventDefault();
    var in_friend_id = $(this).attr("data-id");
    var self = this;
    //
    $.ajax({
      url: "/users/"+in_friend_id+"/friendship",
      type: "POST",
      success: function() {
        console.log("friendship created");
        toggleFriendButtons($(self));
      }
    });

    // $(this).attr("disabled", "disabled");
    // $(this).text("Friending...")
  });



  $("ul").on("click", "button.unfriend", function(event){
    event.preventDefault();
    var in_friend_id = $(this).attr("data-id");
    var self = this;
    //

    $.ajax({
      url: "/users/"+in_friend_id+"/friendship",
      type: "DELETE",
      success: function() {
        console.log("friendship deleted");
        toggleFriendButtons($(self));
      }
    });

  });
</script>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", :user => @user %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<h2>Secrets</h2>

<%= render "secrets/form", recipient_id: @user.id, tags: Tag.all %>

<ul id="secrets">
  <% @user.received_secrets.each do |secret| %>
    <li>
      <%= secret.title %>
      (
        <% secret.tags.each do |tag| %>
          <%= tag.name + " "%>
        <% end %>
       )
    </li>
  <% end %>
</ul>

<script>
  $("#secretForm").on("submit", function(event){
    event.preventDefault();
    var formData = $(this).serialize();
    var form = this;

    $.ajax({
      url: "/secrets",
      type: "POST",
      data: formData,
      error: function(resp) {
        console.log("error error!");
      },
      success: function(resp) {
        console.log("secret created!");
        console.log(resp.secret)

        var tagNamesStr = ""
        for (var i=0; i<resp.tags.length; i++) {
          tagNamesStr += resp.tags[i].name + " ";
        }

        var htmlStr = "<li>"+resp.secret.title+" ( "+ tagNamesStr+")</li>"
        $("ul#secrets").children().first().before(htmlStr);
        console.log(form);
        $("input[type=text]").val("");
      }
    });
  });
</script>